In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("missingvals.csv")


In [4]:
# Insert the mean of all values for the ones which are missing. Then, drop the column with missing values and add the new column.

from sklearn.impute import SimpleImputer

imputer = SimpleImputer() #missing_values=np.nan, strategy='mean' as default

print(data)
age = data.iloc[:,2:4].values

imputer = imputer.fit(age)
age = imputer.transform(age)

age = age[:,-1:]

data = data.drop(['age'],axis=1)

data.insert(3,"age",age)
print(data) 

   country  height  weight   age gender
0       tr     130      30  10.0      e
1       tr     125      36  11.0      e
2       tr     135      34  10.0      k
3       tr     133      30   9.0      k
4       tr     129      38  12.0      e
5       tr     180      90  30.0      e
6       tr     190      80  25.0      e
7       tr     175      90  35.0      e
8       tr     177      60  22.0      k
9       us     185     105  33.0      e
10      us     165      55  27.0      k
11      us     155      50  44.0      k
12      us     160      58   NaN      k
13      us     162      59  41.0      k
14      us     167      62  55.0      k
15      fr     174      70  47.0      e
16      fr     193      90   NaN      e
17      fr     187      80  27.0      e
18      fr     183      88  28.0      e
19      fr     159      40  29.0      k
20      fr     164      66  32.0      k
21      fr     166      56  42.0      k
   country  height  weight    age gender
0       tr     130      30  10.00      

In [5]:
# Convert to one hot encoder and add to the dataframe

from sklearn import preprocessing

le = preprocessing.LabelEncoder()

country = data.iloc[:,0:1].values

country[:,0] = le.fit_transform(country)
print(country)

ohe = preprocessing.OneHotEncoder()

country = ohe.fit_transform(country).toarray()
print(country)

country = pd.DataFrame(data=country, index=range(22), columns = ['fr','tr','us'])
print(country)

data = data.drop(['country'],axis=1)
data = pd.concat([country,data],axis=1)

print(data)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
     fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0
     fr   tr   us  height  weight    age gender
0   0.0  1.0  0.0     130      30  10.00      e
1   0.0  1.0  0.0     125      36  11.00      e
2   0.0  1.0  0.0     135      34  10.00      k
3   0.0  1.0  0.0 

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
